### ISSUE TITLE
FileNotFoundError in graph_cli

### ISSUE THREAD

**Issue by gregwalters** [nccgroup/PMapper#120]
**Describe the bug**
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<user>/Library/Application Support/com.nccgroup.principalmapper/aws-us-gov'

**To Reproduce**
```
git checkout v1.2.0-dev
pip install .
pmapper --profile <my profile> graph create
```

**Expected behavior**
Graph creates correctly.

**Full stacktrace**
```
$ pmapper --profile <my profile> graph create
Traceback (most recent call last):
  File "/usr/local/bin/pmapper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/principalmapper/__main__.py", line 151, in main
    return graph_cli.process_arguments(parsed_args)
  File "/usr/local/lib/python3.9/site-packages/principalmapper/graphing/graph_cli.py", line 160, in process_arguments
    for subdir in org_tree_search_dir.iterdir():
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<my user>/Library/Application Support/com.nccgroup.principalmapper/aws-us-gov'
```

Running this worked around the issue:
```
mkdir Library/Application\ Support/com.nccgroup.principalmapper/aws-us-gov
```

**Comment by cascioli** [comment]
Hi there, I'd like to fix this error by searching in the correct paths and implementing a robust file existence check before execution. Please assign it to me whenever you can. Thanks!
