### ISSUE TITLE
Connection Refused error 40% through IAM Checks

### ISSUE THREAD

**Issue by kbroughton** [nccgroup/PMapper#15]
**Describe the bug**
./pmapper.py  --profile myprofile  graph
40% through IAM Checks
ConnectionRefusedError: [Errno 111] Connection refused 
Could not connect to the endpoint URL: "https://iam.amazonaws.com/"

I also received a similar error for
./pmapper.py  --profile myprofile query "who can do ec2:*"

I am using an sts assume role with mfa.  It is possible that the temp creds from the mfa challenge
are expiring.  If so, definitely need some checkpointing to run graph in phases if possible.  Perhaps a 
pull-raw-data phase per resource type and a process data phase?

**To Reproduce**
Steps to reproduce the behavior, please include information on suspected users/roles that are the source of the issue when possible:

git clone latest PMapper
I have the latest:
commit d38a5decafdc02863024ff866cb3de45050f8bca
Author: ncc-erik-steringer <ncc-erik-steringer@users.noreply.github.com>
Date:   Thu Oct 18 18:18:22 2018 -0700
 Query Updates: Code cleanup, new functionality (#13)

$ ./pmapper.py  --profile myprofile  graph

**Expected behavior**
I expect this is some sort of throttling and there needs to be a more robust handling of errors.  Also, eve though it ran for several hours before crashing, I will have to start from scratch as there seems to be no checkpointing mechanism.  Perhaps writing results to disk in phases would help.

[+] Pulling info on IAM users and roles, finding admins.
Principals Checked: 100%|#########################################################################################################################################################| 360/360 [03:08<00:00,  1.40it/s]
[+] Finished finding admins.
[+] Started EC2 checks.
Principals Checked: 100%|#########################################################################################################################################################| 360/360 [04:43<00:00,  2.00it/s]
[+] Finished EC2 checks.
[+] Started IAM checks.
Principals Checked:  40%|############################################################7                                                                                            | 143/360 [19:02<28:56,  8.00s/it]Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 258, in send
    decode_content=False,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f5147135400>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pmapper.py", line 177, in <module>
    main()
  File "./pmapper.py", line 51, in main
    handle_graph(parsed)
  File "./pmapper.py", line 60, in handle_graph
    graph = pull_graph(parsed.profile)
  File "./pmapper.py", line 137, in pull_graph
    enumerator.fillOutGraph()
  File "/PMapper/principalmap/enumerator.py", line 32, in fillOutGraph
    checkrunner.runChecks()
  File "/PMapper/principalmap/edgeconditions/checkrunner.py", line 50, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/PMapper/principalmap/edgeconditions/iamchecks.py", line 55, in performChecks
    resultlist = test_node_access(iamclient, nodeX, ['sts:AssumeRole'], roles)
  File "/PMapper/principalmap/edgeconditions/util.py", line 59, in test_node_access
    result.extend(_test_less(iamclient, node, action, rlist))
  File "/PMapper/principalmap/edgeconditions/util.py", line 77, in _test_less
    ResourceArns=resourceList
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 179, in _get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 223, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/httpsession.py", line 278, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://iam.amazonaws.com/"
Exception ignored in: <function tqdm.__del__ at 0x7f51493e3730>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.7/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/local/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by ncc-erik-steringer** [comment]
Interesting. I see that the exception is a result of calling the Simulate API, but it's not a ClientError from throttling (which is caught in the latest code in `master`)  but rather a network error. I can put together a patch to handle that as well, but it'll need to be retry-limited (in case someone's actually unable to connect to the endpoint).

Long term, finishing #12 will also help with this issue.
