### ISSUE TITLE
 facing the error "Exception KeyError: KeyError(<weakref at 0x7f80ace22ba8; to 'tqdm' at 0x7f80acd64110>,)"

### ISSUE THREAD

**Issue by nitinitare** [nccgroup/PMapper#3]
Hi @ncc-erik-steringer 

I have installed PMapper and required packages.

When running the command "python pmapper.py --profile Pmapper graph" getting the below error -

Exception KeyError: KeyError(<weakref at 0x7f80ace22ba8; to 'tqdm' at 0x7f80acd64110>,) in <bound method tqdm.__del__ of Princ
ipals Checked:   0%|                                                                                                                                                  | 0/115 [00:09<?, ?it/s]> ignored
Traceback (most recent call last):
  File "pmapper.py", line 174, in <module>
    main()
  File "pmapper.py", line 52, in main
    handle_graph(parsed)
  File "pmapper.py", line 60, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 136, in pull_graph
    enumerator.fillOutGraph()
  File "/root/PMapper/principalmap/enumerator.py", line 33, in fillOutGraph
    checkrunner.runChecks()
  File "/root/PMapper/principalmap/edgeconditions/checkrunner.py", line 51, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/root/PMapper/principalmap/edgeconditions/lambdachecks.py", line 55, in performChecks
    change_testresults = testMass(iamclient, nodeX, ['lambda:UpdateFunctionCode', 'lambda:UpdateFunctionConfiguration', 'lambda:InvokeFunction'], functionarns)
  File "/root/PMapper/principalmap/edgeconditions/util.py", line 38, in testMass
    Marker=response['Marker']
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "PolicySourceArn"
Missing required parameter in input: "ActionNames"
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_monitor.py", line 72, in run
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 106, in __enter__
  File "/usr/local/lib/python2.7/dist-packages/tqdm/_tqdm.py", line 99, in acquire
  File "/usr/lib/python2.7/threading.py", line 168, in acquire
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

![pmapper_error](https://user-images.githubusercontent.com/35133782/41912078-2bafae24-796c-11e8-9f94-bdc365b52230.png)

Any idea how this error can be fixed.

**Comment by ncc-erik-steringer** [comment]
It looks like there's a bug in my code for handling truncated responses (testMass function in /principalmap/edgeconditions/util.py). I'll have to fix that.

**Comment by ncc-erik-steringer** [comment]
@nitinitare , thank you for your patience. I put together an attempted fix in commit 0ca2c9fbb1848380144499f3547b88dec6177feb  under the fix3 branch. Please give it a shot to see if it correctly handles truncated responses.

**Comment by nitinitare** [comment]
Hi @ncc-erik-steringer  I am still getting error while running the query : **python pmapper.py --profile Pmapper graph**


Exception KeyError: KeyError(<weakref at 0x7fd2e1c42db8; to 'tqdm' at 0x7fd2e1e8da50>,) in <bound method tqdm.__del__ of Principals Checked:   0%|                                                                                                                                                    | 0/118 [00:06<?, ?it/s]> ignored
Traceback (most recent call last):
  File "pmapper.py", line 174, in <module>
    main()
  File "pmapper.py", line 52, in main
    handle_graph(parsed)
  File "pmapper.py", line 60, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 136, in pull_graph
    enumerator.fillOutGraph()
  File "/root/PMapper/principalmap/enumerator.py", line 33, in fillOutGraph
    checkrunner.runChecks()
  File "/root/PMapper/principalmap/edgeconditions/checkrunner.py", line 51, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/root/PMapper/principalmap/edgeconditions/lambdachecks.py", line 55, in performChecks
    change_testresults = testMass(iamclient, nodeX, ['lambda:UpdateFunctionCode', 'lambda:UpdateFunctionConfiguration', 'lambda:InvokeFunction'], functionarns)
  File "/root/PMapper/principalmap/edgeconditions/util.py", line 38, in testMass
    Marker=response['Marker']
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "PolicySourceArn"
Missing required parameter in input: "ActionNames"

How the missing parameters can be provided and in which file?

**Comment by ncc-erik-steringer** [comment]
@nitinitare , just to confirm, did you use the code from the `fix3` branch? I haven't merged it into master yet. The `fix3` branch includes those parameters.

The root of this issue appears to be the `testMass` function. That function calls SimulatePrincipalPolicy, but I was calling it with only the Marker parameter instead of the Marker parameter _and_ the original action/resource parameters.

**Comment by nitinitare** [comment]
@ncc-erik-steringer  I have used code from master branch. I will try with the fix3 branch.

**Comment by lidiadjennane** [comment]
@ncc-erik-steringer i tested the code in fix3 branch and still having the same error as @nitinitare .

**Comment by ncc-erik-steringer** [comment]
@lidiadjennane , based on the Traceback there it looks like I have a separate bug to fix for putting in duplicates of a context key.

**Comment by nitinitare** [comment]
@ncc-erik-steringer  I have tried using fix3 branch, still getting the error.

[+] Pulling info on IAM users and roles, finding admins.
Principals Checked:   1%|#1                                                                                                                                          | 1/118 [00:01<02:01,  1.04s/it]Principals Checked: 100%|##########################################################################################################################################| 118/118 [00:59<00:00,  1.98it/s]
[+] Finished finding admins.
[+] Started EC2 checks.
Principals Checked: 100%|##########################################################################################################################################| 118/118 [01:33<00:00,  1.26it/s]
[+] Finished EC2 checks.
[+] Started IAM checks.
Principals Checked: 100%|##########################################################################################################################################| 118/118 [01:33<00:00,  1.26it/s]
[+] Finished IAM checks.
[+] Starting Lambda checks.
Regions Checked for Lambda Functions: 100%|##########################################################################################################################| 15/15 [00:15<00:00,  1.04s/it]
Principals Checked:   0%|                                                                                                                                                    | 0/118 [00:00<?, ?it/s]Traceback (most recent call last):
  File "pmapper.py", line 174, in <module>
    main()
  File "pmapper.py", line 52, in main
    handle_graph(parsed)
  File "pmapper.py", line 60, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 136, in pull_graph
    enumerator.fillOutGraph()
  File "/root/PMapper/PMapper/principalmap/enumerator.py", line 33, in fillOutGraph
    checkrunner.runChecks()
  File "/root/PMapper/PMapper/principalmap/edgeconditions/checkrunner.py", line 51, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/root/PMapper/PMapper/principalmap/edgeconditions/lambdachecks.py", line 55, in performChecks
    change_testresults = testMass(iamclient, nodeX, ['lambda:UpdateFunctionCode', 'lambda:UpdateFunctionConfiguration', 'lambda:InvokeFunction'], functionarns)
  File "/root/PMapper/PMapper/principalmap/edgeconditions/util.py", line 38, in testMass
    Marker=response['Marker']
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "PolicySourceArn"
Missing required parameter in input: "ActionNames"

**Comment by ncc-erik-steringer** [comment]
Alright. My next refactoring attempt will compose a list of action/resource tuples and feed small chunks of them to the API to test. That should address this issue and another one that a pull-request is trying to fix. I'll test with 100 Lambda functions in my account before I merge.

**Comment by kmcquade** [comment]
@ncc-erik-steringer - I'm getting this as well. Does it work with a previous version of botocore? I see that you didn't specify required versions in requirements.txt.

**Comment by ncc-erik-steringer** [comment]
Made another commit to attempt to address this issue. It handled 100 (101?) Lambda functions I believe. I still want to verify I'm pulling all of the Lambda functions down (not just a small group).

**Comment by nitinitare** [comment]
@ncc-erik-steringer has it been fixed?

**Comment by ncc-erik-steringer** [comment]
@nitinitare I think I fixed your particular use-case with the latest commit to the fix3 branch, a large amount of Lambda functions, by chunking out the number of resources given to the SimulatePrincipalPolicy API.

**Comment by nitinitare** [comment]
@ncc-erik-steringer I have tried with fix4 branch and still got the errors.

[+] Pulling info on IAM users and roles, finding admins.
Principals Checked: 100%|##########################################################################################################################################| 370/370 [03:11<00:00,  1.94it/s]
[+] Finished finding admins.
[+] Started EC2 checks.
Principals Checked:   7%|#########3                                                                                                                                 | 25/370 [02:07<29:25,  5.12s/it]Traceback (most recent call last):
  File "pmapper.py", line 172, in <module>
    main()
  File "pmapper.py", line 52, in main
    handle_graph(parsed)
  File "pmapper.py", line 60, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 134, in pull_graph
    enumerator.fillOutGraph()
  File "/root/PMapper/principalmap/enumerator.py", line 33, in fillOutGraph
    checkrunner.runChecks()
  File "/root/PMapper/principalmap/edgeconditions/checkrunner.py", line 50, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/root/PMapper/principalmap/edgeconditions/ec2checks.py", line 68, in performChecks
    passable = testMassPass(iamclient, nodeX, withprofiles, 'ec2.amazonaws.com')
  File "/root/PMapper/principalmap/edgeconditions/util.py", line 134, in testMassPass
    ContextEntries=context_entries
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
socket.error: [Errno 104] Connection reset by peer

**Comment by nitinitare** [comment]
Hi @ncc-erik-steringer, is the bug fixed?

**Comment by ncc-erik-steringer** [comment]
@nitinitare , not yet. Expecting to be able to wrap it up a week from today.

**Comment by ncc-erik-steringer** [comment]
@nitinitare , I applied the chunking pattern to `testMassPass`. That _should_ resolve the bug in your case.

**Comment by nitinitare** [comment]
Hi @ncc-erik-steringer, this time i got the diffrent error. please have a look at it and let me know what is the issue.

[+] Pulling info on IAM users and roles, finding admins.
Principals Checked: 100%|##########################################################################################################################################| 383/383 [03:15<00:00,  1.96it/s]
[+] Finished finding admins.
[+] Started EC2 checks.
Principals Checked: 100%|##########################################################################################################################################| 383/383 [07:33<00:00,  1.18s/it]
[+] Finished EC2 checks.
[+] Started IAM checks.
Principals Checked: 100%|##########################################################################################################################################| 383/383 [10:49<00:00,  1.70s/it]
[+] Finished IAM checks.
[+] Starting Lambda checks.
Regions Checked for Lambda Functions: 100%|##########################################################################################################################| 15/15 [00:17<00:00,  1.18s/it]
Principals Checked: 100%|######################################################################################################################################| 383/383 [11:20:39<00:00, 106.63s/it]
[+] Finished Lambda checks.
Traceback (most recent call last):
  File "pmapper.py", line 176, in <module>
    main()
  File "pmapper.py", line 50, in main
    handle_graph(parsed)
  File "pmapper.py", line 59, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 136, in pull_graph
    enumerator.fillOutGraph()
  File "/root/PMapper/principalmap/enumerator.py", line 32, in fillOutGraph
    checkrunner.runChecks()
  File "/root/PMapper/principalmap/edgeconditions/checkrunner.py", line 51, in runChecks
    self.graph.edges.extend(edgelist)
MemoryError

**Comment by ncc-erik-steringer** [comment]
@nitinitare , this is a separate bug at this point. Either your computer doesn't have enough memory or your resulting graph is absolutely massive. If you're running this in EC2, try an instance with some more memory (triple it). You could also add a print statement in /principalmap/edgeconditions/checkrunner.py to get the length of the edgelist so we know what we're dealing with.

**Comment by ncc-erik-steringer** [comment]
@nitinitare , if you are willing, I've just pushed up v1.0.0: https://github.com/nccgroup/PMapper/releases/tag/v1.0.0 

I'm not sure if you were running on a limited-resource machine, but I think this update should reduce the amount of AWS API requests (avoiding throttling). It may have a greater memory footprint. Please take a shot with the new version.
