### ISSUE TITLE
ThrottlingException is not defined

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/PMapper#9]
Getting this exception / traceback while running pmapper:
```
Traceback (most recent call last):
  File "pmapper.py", line 176, in <module>
    main()
  File "pmapper.py", line 50, in main
    handle_graph(parsed)
  File "pmapper.py", line 59, in handle_graph
    graph = pull_graph(parsed.profile)
  File "pmapper.py", line 136, in pull_graph
    enumerator.fillOutGraph()
  File "/home/eth/tools/PMapper/principalmap/enumerator.py", line 32, in fillOutGraph
    checkrunner.runChecks()
  File "/home/eth/tools/PMapper/principalmap/edgeconditions/checkrunner.py", line 50, in runChecks
    edgelist = checker.performChecks(self.session, self.graph.nodes)
  File "/home/eth/tools/PMapper/principalmap/edgeconditions/iamchecks.py", line 44, in performChecks
    resultlist = test_node_access(iamclient, nodeX, ['iam:CreateAccessKey', 'iam:UpdateLoginProfile', 'iam:CreateLoginProfile'], users)
  File "/home/eth/tools/PMapper/principalmap/edgeconditions/util.py", line 59, in test_node_access
    result.extend(_test_less(iamclient, node, action, rlist))
  File "/home/eth/tools/PMapper/principalmap/edgeconditions/util.py", line 80, in _test_less
    except ThrottlingException as ex:
NameError: global name 'ThrottlingException' is not defined
Exception KeyError: KeyError(<weakref at 0x7fa8cabba998; to 'tqdm' at 0x7fa8d3cba110>,) in <bound method tqdm.__del__ of Principals Checked:   2%|###2                                                                                                                                      | 158/6640 [9:08:19<326:52:34, 181.54s/it]> ignored
```

"Fixed it" with:
```
diff --git a/principalmap/edgeconditions/cloudformationchecks.py b/principalmap/edgeconditions/cloudformationchecks.py
index 8b3f8f8..437cf76 100644
--- a/principalmap/edgeconditions/cloudformationchecks.py
+++ b/principalmap/edgeconditions/cloudformationchecks.py
@@ -52,7 +52,7 @@ class CloudFormationChecker():
                     try:
                         fullstacks = cfclient.describe_stacks(StackName=item['StackId'])
                         stack_retrieved = True
-                    except ThrottlingException as ex:
+                    except Exception as ex:
                         print('ThrottlingException hit, pausing execution for one second.')
                         time.sleep(1)  # TODO: implement escalate and backoff behavior
 
diff --git a/principalmap/edgeconditions/util.py b/principalmap/edgeconditions/util.py
index 69b241a..033a419 100644
--- a/principalmap/edgeconditions/util.py
+++ b/principalmap/edgeconditions/util.py
@@ -77,7 +77,7 @@ def _test_less(iamclient, node, action, resourceList):
                 ResourceArns=resourceList
             )
             done = True
-        except ThrottlingException as ex:
+        except Exception as ex:
             print('ThrottlingException hit, pausing execution for one second.')
             time.sleep(1)
             # TODO: implement escalate and backoff behavior
```

Had to use the ugly `except Exception` catch because I was unable to find the definition for `ThrottlingException` in `boto` or `botocore`.

**Comment by ncc-erik-steringer** [comment]
I recently pushed a fix that chunks out requests checking on access to iam:PassRole. That commit (  1c90427 ) changes to the code to catch botocore.exceptions.ClientError and checks if the error code includes the string "Thrott" (for Throttle or ThrottlingException).
